try 
    
    a = 1 + 1
    
    error('this is an error')
    
    b = 2 + 2
    
catch
    
    b = 4 + 4
    
end